import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { prisma } from "@/lib/prisma";
import { generatePalette } from "@/lib/colorUtils";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: process.env.NEXT_PUBLIC_CLUB_NAME || "Tennis Club",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  let primaryColor = "#4f46e5"; // default primary-600
  try {
    const settings = await prisma.systemSetting.findUnique({ where: { id: "global" } });
    if (settings?.primaryColor) {
      primaryColor = settings.primaryColor;
    }
  } catch (err) {
    console.error("Failed to load global settings for layout", err);
  }

  const palette = generatePalette(primaryColor);
  const themeStyles = `
    :root {
      ${Object.entries(palette).map(([weight, hex]) => `--primary-${weight}: ${hex};`).join('\n      ')}
    }
  `;

  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <head>
        <style dangerouslySetInnerHTML={{ __html: themeStyles }} />
      </head>
      <body className="min-h-full flex flex-col">{children}</body>
    </html>
  );
}
